<?php if ($error != null){?>
  <p><?= $error ?></p>
<?php } ?>


<div class="container other-cont">

<h3>Connectez-vous !</h3>

<form action="<?=$requestUrl?>/user/login" method="POST">

<ul>
  <li>
    <label for="email">
    Votre Adresse E-mail :</label>
    <input type="email" name="email" placeholder="email">
  </li>

  <li>
    Votre Mot de passe :
    <input type="password" name="password" placeholder="password">
  </li>
</ul>

<input type="submit" value="Connexion">

</form>

</div>
