<link rel="stylesheet" href="<?= $wwwUrl ?>/css/register.css">

<div class="container other-cont">

	<h2>Enregistrez vous !</h2>

	<form class="" action="<?=$requestUrl?>/user/register" method="POST">

		<ul class="register">
			<li>
				<label for="Firstname">Votre prénom :</label>
				<input class="form-control" type="text" name="firstname" placeholder="Prénom" id="Firstname">
			</li>

			<li>
				<label for="Lastname">Votre nom :</label>
				<input class="form-control" type="text" name="lastname" placeholder="Nom" id="Lastname" required>
			</li>

			<li>
				<label for="phone">Numéro de téléphone :</label>
				<input class="form-control" type="tel" name="phone" id="phone">
			</li>

			<li>
				<label for="email">Adresse e-mail :</label>
				<input class="form-control" type="email" name="email" placeholder="email" id="email" required>
			</li>

			<li>
				<label for="passw">Choisir un mot de passe :</label>
				<input class="form-control" type="password" name="password" placeholder="Mot de passe" id="passw" minlength="8" required>
			</li>

			<li>
				<label for="birthday">Votre date de naissance :</label>
		    <input class="form-control" type="date" name="birthday" id="birthday">
			</li>

			<li>
				<label for="adress">Votre adresse :</label>
				<input class="form-control" type="text" name="adress" placeholder="Adresse" id="adress" required>
			</li>

			<li>
				<label for="ville">Ville :</label>
				<input class="form-control" type="text" name="city" placeholder="Ville" id="ville" required>
			</li>

			<li>
				<label for="zip">Code Postale :</label>
				<input class="formcontrol" type="text" name="zip" placeholder="Code postal" id="zip" required>
			</li>

			<li>
				<label for="country">Pays :</label>
				<input class="formcontrol" type="country" name="country" id="country">
			</li>
		</ul>
		<br>
		<div class="sub">

			<input class="form-control" type="submit" value="Enregister">
		</div>
	</form>
</div
