<div class="container">

	<h3>Enregistrez vous !</h3>

	<form class="" action="<?=$requestUrl?>/user/register" method="POST">

    <label for="Firstname">Votre prénom :</label>
		<input class="form-control" type="text" name="firstname" placeholder="Prénom" id="Firstname">

    <label for="Lastname">Votre nom :</label>
		<input class="form-control" type="text" name="lastname" placeholder="Nom" id="Lastname" required>

    <label for="phone">Numéro de téléphone :</label>
    <input class="form-control" type="tel" name="phone" id="phone">

    <label for="email">Adresse e-mail :</label>
		<input class="form-control" type="email" name="email" placeholder="email" id="email" required>

    <label for="passw">Choisir un mot de passe :</label>
		<input class="form-control" type="password" name="password" placeholder="Mot de passe" id="passw" minlength="8" required>

    <label for="birthday">Votre date de naissance :</label>
    <input class="form-control" type="date" name="birthday" id="birthday">

    <label for="adress">Votre adresse :</label>
		<input class="form-control" type="text" name="adress" placeholder="Adresse" id="adress" required>

    <label for="ville">Ville :</label>
		<input class="form-control" type="text" name="city" placeholder="Ville" id="ville" required>

    <label for="zip">Code Postale :</label>
		<input class="formcontrol" type="text" name="zip" placeholder="Code postal" id="zip" required>

    <label for="country">Pays :</label>
    <input class="formcontrol" type="country" name="country" id="country">

		<input class="form-control" type="submit" value="Enregister">
	</form>
</div
