  <script src="https://kit.fontawesome.com/a076d05399.js"></script>

<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestation.css">

<header>
    <h1 class="title">Prestation et Services</h1>
</header>

  <main>
    <section class="main-article-flex">
      <article class="article-flex">
        <div class="inside">
          <img src="<?= $wwwUrl ?>/images/prestation/flower-crown1.jpg" alt="baby">
          <h2>Disponibilites</h2>
          <p>Nous sommes disponibles du Lundi au Dimanche, pendant les vacances scolaires ainsi que les jours fériés.</p>
          <p>Nous sommes également à votre disposition pour vous rencontrer.</p>
        </div>
      </article>
      <article class="article-flex">
        <div class="inside">
          <img src="<?= $wwwUrl ?>/images/prestation/baby-crown.jpg" alt="article">
          <h2>horaires</h2>
          <p>Nous proposons une plage horaire selon vos besoins personnels.</p>
          <p>Ce sont généralement des nuits d'une durée comprise entre 9 et 12 heures.</p>
          <p>Possibilité de se rendre plus tôt à votre domicile et de rester plus tard le matin.</p>
        </div>
      </article>
      <article class="article-flex">
        <div class="inside">
          <img src="<?= $wwwUrl ?>/images/prestation/flower-crown2.jpg" alt="article">
          <h2>Tarif</h2>
          <p>Variable selon le nombre d'heures demandées et si il s'agit d'une grossesse simple ou gémellaire.</p>
          <p>La déclaration des nuits est possible sur le site <a href="https://www.cesu.urssaf.fr/info/accueil.html">CESU</a> ou sur <a href="https://www.pajemploi.urssaf.fr/pajewebinfo/cms/sites/pajewebinfo/accueil.html">PAJEMPLOI</a></p>
        </div>
      </article>
    </section>
    <hr>
    <div class="infos">

      <p>Pour plus de renseignements; <strong>N'hésitez pas</strong> à nous contacter par <strong>téléphone</strong> et/ou par mail.</p>
      <a href="tel:+33633687410"><img src="<?= $wwwUrl ?>/images/prestation/phone.png" alt="call"></a>
      <a href="mailto:retour-maternite@outlook.fr"><img src="<?= $wwwUrl ?>/images/prestation/mail.png" alt="mail"></a>
    </div>

    <div class="special-btn">
    <a href="<?= $requestUrl ?>">Revenir à la page d'accueil <i class="fas fa-undo-alt"></i></a>
    </div>
  </main>
