<link rel="stylesheet" href="<?= $wwwUrl ?>/css/reservation.css">


<form>

  <div class="form-group">
    <label for="lieu">Lieu de la garde</label>
    <input type="text" class="form-control" id="lieu">
  </div>

</div>


<label for="date">Je choisi la date à laquelle je souhaiterais une nurse</label>
<input type="date" name="date" id="dateofbirth">

<p>Pour quel moment avez vous besoin d'une garde ? :</p>

<div>
  <input type="checkbox" id="jour" name="jour">
  <label for="jour">La journée</label>
</div>

<div>
  <input type="checkbox" id="nuit" name="nuit">
  <label for="nuit">La soirée / Nuit</label>
</div>

</form>
