<link rel="stylesheet" href="<?= $wwwUrl ?>/css/reservation.css">

<div class="container other-cont">

	<h3>Reserver une garde !</h3>


	<form action="<?=$requestUrl?>/reservation" method="POST">

		<ul>
			<li>
				<label for="date">Je choisi la date à laquelle je souhaiterais réserver une nurse</label>
			  <input type="date" name="day" id="dateofbirth">
			</li>

			<li>
				<label for="adress">Adresse Postale</label>
				<input type="text" name="adress" id="adress">
			</li>

			<li>
				<label for="lieu">Ville</label>
				<input type="text" name="city" id="lieu">
			</li>

			<li>
				<label for="hour">Horaire de la garde</label>
			  <input type="time" name="hour" id="hour"  min="00:00" max="24:00" >
			</li>
		</ul>
		
	<input class="form-control" type="submit" value="Enregister">

</form>

</div>
