<link rel="stylesheet" href="<?= $wwwUrl ?>/css/reservation.css">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<h2 class="title">Liste des réservations à venir</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nom & Prénom</th>
      <th scope="col">Numéro de téléphone</th>
      <th scope="col">Horaire de la réservation</th>
      <th scope="col">Date de la reservation</th>
      <th scope="col">Email</th>
      <th>

      </th>
      <!-- <th scope="col">Adresse de la famille</th> -->
      <!-- <th scope="col">Date d'inscription</th> -->
    </tr>
  </thead>
  <tbody>
    <?php foreach($reservations as $reservation) {?>
      <tr>
        <td scope="row"><?=$reservation['FirstName']?> <?=$reservation['LastName']?></td>
        <td>(0)<?=$reservation['Phone']?></td>
        <td><?=$reservation['Hour']?></td>
        <td><?=$reservation['Day']?></td>
        <td><?=$reservation['Email']?></td>
        <td>
          <a href="<?=$requestUrl ?>/admin/reservation/delete?id=<?=$reservation['Id']?>"> Supprimer</a>
        </td>
      </tr>
    <?php }?>
  </tbody>
</table>
