<link rel="stylesheet" href="<?= $wwwUrl ?>/css/profil.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/register.css">

<section class="flex">


<div class="other-cont">
  <h2>Mon Profil</h2>

  <p>Pour modifier vos informations, veuillez directement modifier le champs et cliquez sur "Modifier mes informations" une fois terminé  </p>

  <form action="<?=$requestUrl?>/user/profil" method="POST">
    <ul class="register">
      <li>
        <label for="firstname">Votre prénom :</label>
        <input type="text" name="firstname" placeholder="Prénom" value="<?=$user['FirstName']?>">
      </li>
      <li>
        <label for="lastname">Votre nom :</label>
        <input type="text" name="lastname" placeholder="Nom" value="<?=$user['LastName']?>">
      </li>
      <li>
        <label for="email">Adresse e-mail :</label>
        <input type="text" name="email" placeholder="email" value="<?=$user['Email']?>">
      </li>
      <li>
        <label for="adress">Votre adresse :</label>
        <input type="text" name="address" placeholder="Adresse" value="<?=$user['Adress']?>">
      </li>
      <li>
        <label for="ville">Ville :</label>
        <input type="text" name="city" placeholder="Ville" value="<?=$user['City']?>">
      </li>
      <li>
        <label for="zip">Code Postale :</label>
        <input type="text" name="zip" placeholder="Code postal" value="<?=$user['Zip']?>">
      </li>
    </ul>
    <div class="sub">
      <input type="submit" value="Modifier mes informations">
    </div>
  </form>

</div>

<div class="other-cont">
  <h2>Mes reservations à venir</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Jour</th>
        <th scope="col">Horaire</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($reservation as $reservations) {?>
        <tr>
          <td><?=$reservations['Day']?></td>
          <td><?=$reservations['Hour']?></td>
          <td>
            <a href="<?=$requestUrl ?>/user/profil/delete?id=<?=$reservations['Id']?>"> Supprimer</a>
          </td>
        </tr>
      <?php }?>
    </tbody>
  </table>
</div>

</section>
